stages:
  generate_data:
    cmd: python src/generate_data.py
    deps:
    - src/generate_data.py
    outs:
    - data/test_x/artifacts
    - data/test_x/mlem.yaml:
        cache: false
    - data/test_y/artifacts
    - data/test_y/mlem.yaml:
        cache: false
    - data/train/artifacts
    - data/train/mlem.yaml:
        cache: false
  train:
    cmd: python src/train.py data/train data/model
    deps:
    - data/train
    - src/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - data/model/artifacts
    - data/model/mlem.yaml:
        cache: false
  predict:
    cmd: mlem apply latest data/test_x -m predict_proba -o data/pred
    deps:
    - data/model
    - data/test_x
    outs:
    - data/pred/artifacts
    - data/pred/mlem.yaml:
        cache: false
  score:
    cmd: python src/score.py data/pred data/test_y scores.json
    deps:
    - data/pred
    - data/test_y
    - src/score.py
    outs:
    - scores.json:
        cache: false
